In [ ]:
#Natural Language Toolkit for Natural Language Processing
!pip install autocorrect

Requirement already satisfied: autocorrect in /usr/local/lib/python3.7/dist-packages (2.6.1)

Import neccasary libraries and import data from github

In [ ]:
import pandas as pd

import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

import string
import re
import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS
comment_words = ' '
stopwords = set(STOPWORDS) 
from autocorrect import Speller
from nltk.tokenize import WhitespaceTokenizer
from nltk import word_tokenize
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [ ]:
def clean_text(text):
    # remove numbers
    text_nonum = re.sub(r'\d+', '', text)
    # remove punctuations and convert characters to lower case
    text_nopunct = "".join([char.lower() for char in text_nonum if char not in string.punctuation]) 
    # substitute multiple whitespace with single whitespace
    # Also, removes leading and trailing whitespaces
    text_no_doublespace = re.sub('\s+', ' ', text_nopunct).strip()
    return text_no_doublespace

#Code for Post_Text

In [ ]:
ocd1 = pd.read_csv("https://raw.githubusercontent.com/SrushtiChauhan/Test-2022/main/OCD_comments_main.csv", 
                          on_bad_lines='skip');

In [ ]:
print('OCD Posts data:', ocd1.shape)

HIV Posts data: (845, 5)

In [ ]:
#Data Cleaning
ocd1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              996 non-null    object
 1   Post_Text       996 non-null    object
 2   Total_Comments  996 non-null    int64
 3   Score           996 non-null    int64
 4   Post_Created    996 non-null    object
dtypes: int64(2), object(3)
memory usage: 39.0+ KB

In [ ]:
ocd1.describe()

       Total_Comments        Score
count      996.000000   996.000000
mean         6.109438    10.388554
std         19.230761    45.365502
min          0.000000     0.000000
25%          1.000000     1.000000
50%          2.000000     2.000000
75%          5.000000     5.000000
max        337.000000  1009.000000

In [ ]:
ocd1.isnull().sum()

ID                0
Post_Text         0
Total_Comments    0
Score             0
Post_Created      0
dtype: int64

In [ ]:
# drop all rows with any NaN and NaT values
ocd1 = ocd1.dropna()

In [ ]:
ocd1.isnull().sum()

ID                0
Post_Text         0
Total_Comments    0
Score             0
Post_Created      0
dtype: int64

In [ ]:
# Selecting duplicate rows except first
# occurrence based on all columns
duplicate = ocd1[ocd1.duplicated()]
 
print("Duplicate Rows :")
 
# Print the resultant Dataframe
duplicate

Duplicate Rows :

Empty DataFrame
Columns: [ID, Post_Text, Total_Comments, Score, Post_Created]
Index: []

In [ ]:
#Data Pre-Processing
ocd1.columns

Index(['ID', 'Post_Text', 'Total_Comments', 'Score', 'Post_Created'], dtype='object')

In [ ]:
ocd1.head(3)

,ID,Post_Text,Total_Comments,Score,Post_Created
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00

In [ ]:
#Convert comments data into lower case
ocd1['clean_text'] = ocd1["Post_Text"].str.lower()
ocd1

,ID,Post_Text,Total_Comments,Score,Post_Created,clean_text
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00,please read this before posting about feeling ...
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00,note about rules and reporting to mods mod-mai...
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00,does it bother anyone else how being mentally ...
3,txkoyq,why do thoughts feel so believable? I have to ...,14,27,2022-04-06 08:09:40-04:00,why do thoughts feel so believable? i have to ...
4,txl82i,Im proud of myself Yeah finally ate breakfast ...,2,15,2022-04-06 08:39:10-04:00,im proud of myself yeah finally ate breakfast ...
...,...,...,...,...,...,...
991,tq182f,Awful intrusive thoughts and hard to fight com...,1,7,2022-03-28 00:30:18-04:00,awful intrusive thoughts and hard to fight com...
992,tq5whw,What is happening to me ? Hello\n\nJust some r...,0,2,2022-03-28 06:03:19-04:00,what is happening to me ? hello\n\njust some r...
993,tq0med,How to stop thinking about “what could have be...,1,6,2022-03-27 23:53:54-04:00,how to stop thinking about “what could have be...
994,tq1kii,FEAR ocd Who else feels like they are fearful ...,1,4,2022-03-28 00:51:46-04:00,fear ocd who else feels like they are fearful ...
995,tq2ndk,Manifesting So are we all just manifesting our...,2,5,2022-03-28 02:02:21-04:00,manifesting so are we all just manifesting our...

In [ ]:
#Remove punctuation and special characters from text data
ocd1["clean_text"] = [clean_text(t) for t in ocd1['clean_text']]
ocd1

,ID,Post_Text,Total_Comments,Score,Post_Created,clean_text
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00,please read this before posting about feeling ...
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00,note about rules and reporting to mods modmail...
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00,does it bother anyone else how being mentally ...
3,txkoyq,why do thoughts feel so believable? I have to ...,14,27,2022-04-06 08:09:40-04:00,why do thoughts feel so believable i have to i...
4,txl82i,Im proud of myself Yeah finally ate breakfast ...,2,15,2022-04-06 08:39:10-04:00,im proud of myself yeah finally ate breakfast ...
...,...,...,...,...,...,...
991,tq182f,Awful intrusive thoughts and hard to fight com...,1,7,2022-03-28 00:30:18-04:00,awful intrusive thoughts and hard to fight com...
992,tq5whw,What is happening to me ? Hello\n\nJust some r...,0,2,2022-03-28 06:03:19-04:00,what is happening to me hello just some resume...
993,tq0med,How to stop thinking about “what could have be...,1,6,2022-03-27 23:53:54-04:00,how to stop thinking about “what could have be...
994,tq1kii,FEAR ocd Who else feels like they are fearful ...,1,4,2022-03-28 00:51:46-04:00,fear ocd who else feels like they are fearful ...
995,tq2ndk,Manifesting So are we all just manifesting our...,2,5,2022-03-28 02:02:21-04:00,manifesting so are we all just manifesting our...

In [ ]:
#Autocorrect and spelling mistake correction
#spell = Speller(lang='en')

#ocd1["clean_text"] = [spell(t) for t in ocd1["clean_text"]]
#ocd1

In [ ]:
#Tokenization
# Create a reference variable for Class WhitespaceTokenizer
tk = WhitespaceTokenizer()

ocd1["tokenization"] = [tk.tokenize(t) for t in ocd1["clean_text"]]
ocd1

,ID,Post_Text,Total_Comments,Score,Post_Created,clean_text,tokenization
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00,please read this before posting about feeling ...,"[please, read, this, before, posting, about, f..."
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00,note about rules and reporting to mods modmail...,"[note, about, rules, and, reporting, to, mods,..."
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00,does it bother anyone else how being mentally ...,"[does, it, bother, anyone, else, how, being, m..."
3,txkoyq,why do thoughts feel so believable? I have to ...,14,27,2022-04-06 08:09:40-04:00,why do thoughts feel so believable i have to i...,"[why, do, thoughts, feel, so, believable, i, h..."
4,txl82i,Im proud of myself Yeah finally ate breakfast ...,2,15,2022-04-06 08:39:10-04:00,im proud of myself yeah finally ate breakfast ...,"[im, proud, of, myself, yeah, finally, ate, br..."
...,...,...,...,...,...,...,...
991,tq182f,Awful intrusive thoughts and hard to fight com...,1,7,2022-03-28 00:30:18-04:00,awful intrusive thoughts and hard to fight com...,"[awful, intrusive, thoughts, and, hard, to, fi..."
992,tq5whw,What is happening to me ? Hello\n\nJust some r...,0,2,2022-03-28 06:03:19-04:00,what is happening to me hello just some resume...,"[what, is, happening, to, me, hello, just, som..."
993,tq0med,How to stop thinking about “what could have be...,1,6,2022-03-27 23:53:54-04:00,how to stop thinking about “what could have be...,"[how, to, stop, thinking, about, “what, could,..."
994,tq1kii,FEAR ocd Who else feels like they are fearful ...,1,4,2022-03-28 00:51:46-04:00,fear ocd who else feels like they are fearful ...,"[fear, ocd, who, else, feels, like, they, are,..."
995,tq2ndk,Manifesting So are we all just manifesting our...,2,5,2022-03-28 02:02:21-04:00,manifesting so are we all just manifesting our...,"[manifesting, so, are, we, all, just, manifest..."

In [ ]:
ocd1['tokenization'] = ocd1['tokenization'].apply(lambda x: [w for w in x if not w in 
                              stopwords.words('english')]) # Stem every word.
ocd1 # Print dataframe.

,ID,Post_Text,Total_Comments,Score,Post_Created,clean_text,tokenization
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00,please read this before posting about feeling ...,"[please, read, posting, feeling, suicidal, inc..."
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00,note about rules and reporting to mods modmail...,"[note, rules, reporting, mods, modmail, debate..."
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00,does it bother anyone else how being mentally ...,"[bother, anyone, else, mentally, ill, “normali..."
3,txkoyq,why do thoughts feel so believable? I have to ...,14,27,2022-04-06 08:09:40-04:00,why do thoughts feel so believable i have to i...,"[thoughts, feel, believable, imagine, i’m, cer..."
4,txl82i,Im proud of myself Yeah finally ate breakfast ...,2,15,2022-04-06 08:39:10-04:00,im proud of myself yeah finally ate breakfast ...,"[im, proud, yeah, finally, ate, breakfast, mor..."
...,...,...,...,...,...,...,...
991,tq182f,Awful intrusive thoughts and hard to fight com...,1,7,2022-03-28 00:30:18-04:00,awful intrusive thoughts and hard to fight com...,"[awful, intrusive, thoughts, hard, fight, comp..."
992,tq5whw,What is happening to me ? Hello\n\nJust some r...,0,2,2022-03-28 06:03:19-04:00,what is happening to me hello just some resume...,"[happening, hello, resume, maybe, understand, ..."
993,tq0med,How to stop thinking about “what could have be...,1,6,2022-03-27 23:53:54-04:00,how to stop thinking about “what could have be...,"[stop, thinking, “what, could, been”, keep, ge..."
994,tq1kii,FEAR ocd Who else feels like they are fearful ...,1,4,2022-03-28 00:51:46-04:00,fear ocd who else feels like they are fearful ...,"[fear, ocd, else, feels, like, fearful, every,..."
995,tq2ndk,Manifesting So are we all just manifesting our...,2,5,2022-03-28 02:02:21-04:00,manifesting so are we all just manifesting our...,"[manifesting, manifesting, problems, what’s]"

In [ ]:
ps = PorterStemmer()

In [ ]:
#Stemming
ocd1['stemming'] = ocd1['tokenization'].apply(lambda x: [ps.stem(y) for y in x]) # Stem every word.
ocd1 # Print dataframe.

,ID,Post_Text,Total_Comments,Score,Post_Created,clean_text,tokenization,stemming
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00,please read this before posting about feeling ...,"[please, read, posting, feeling, suicidal, inc...","[pleas, read, post, feel, suicid, increas, num..."
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00,note about rules and reporting to mods modmail...,"[note, rules, reporting, mods, modmail, debate...","[note, rule, report, mod, modmail, debat, club..."
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00,does it bother anyone else how being mentally ...,"[bother, anyone, else, mentally, ill, “normali...","[bother, anyon, els, mental, ill, “normalized”..."
3,txkoyq,why do thoughts feel so believable? I have to ...,14,27,2022-04-06 08:09:40-04:00,why do thoughts feel so believable i have to i...,"[thoughts, feel, believable, imagine, i’m, cer...","[thought, feel, believ, imagin, i’m, certain, ..."
4,txl82i,Im proud of myself Yeah finally ate breakfast ...,2,15,2022-04-06 08:39:10-04:00,im proud of myself yeah finally ate breakfast ...,"[im, proud, yeah, finally, ate, breakfast, mor...","[im, proud, yeah, final, ate, breakfast, morn,..."
...,...,...,...,...,...,...,...,...
991,tq182f,Awful intrusive thoughts and hard to fight com...,1,7,2022-03-28 00:30:18-04:00,awful intrusive thoughts and hard to fight com...,"[awful, intrusive, thoughts, hard, fight, comp...","[aw, intrus, thought, hard, fight, compuls, gu..."
992,tq5whw,What is happening to me ? Hello\n\nJust some r...,0,2,2022-03-28 06:03:19-04:00,what is happening to me hello just some resume...,"[happening, hello, resume, maybe, understand, ...","[happen, hello, resum, mayb, understand, situa..."
993,tq0med,How to stop thinking about “what could have be...,1,6,2022-03-27 23:53:54-04:00,how to stop thinking about “what could have be...,"[stop, thinking, “what, could, been”, keep, ge...","[stop, think, “what, could, been”, keep, get, ..."
994,tq1kii,FEAR ocd Who else feels like they are fearful ...,1,4,2022-03-28 00:51:46-04:00,fear ocd who else feels like they are fearful ...,"[fear, ocd, else, feels, like, fearful, every,...","[fear, ocd, els, feel, like, fear, everi, nois..."
995,tq2ndk,Manifesting So are we all just manifesting our...,2,5,2022-03-28 02:02:21-04:00,manifesting so are we all just manifesting our...,"[manifesting, manifesting, problems, what’s]","[manifest, manifest, problem, what’]"

In [ ]:
lemmatizer = WordNetLemmatizer()

In [ ]:
#Lemmatization
# a denotes adjective in "pos"
ocd1['lemmatizing'] = ocd1['stemming'].apply(lambda x: [lemmatizer.lemmatize(y, pos ="a") for y in x]) # Stem every word.
ocd1 # Print dataframe.

,ID,Post_Text,Total_Comments,Score,Post_Created,clean_text,tokenization,stemming,lemmatizing
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00,please read this before posting about feeling ...,"[please, read, posting, feeling, suicidal, inc...","[pleas, read, post, feel, suicid, increas, num...","[pleas, read, post, feel, suicid, increas, num..."
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00,note about rules and reporting to mods modmail...,"[note, rules, reporting, mods, modmail, debate...","[note, rule, report, mod, modmail, debat, club...","[note, rule, report, mod, modmail, debat, club..."
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00,does it bother anyone else how being mentally ...,"[bother, anyone, else, mentally, ill, “normali...","[bother, anyon, els, mental, ill, “normalized”...","[bother, anyon, els, mental, ill, “normalized”..."
3,txkoyq,why do thoughts feel so believable? I have to ...,14,27,2022-04-06 08:09:40-04:00,why do thoughts feel so believable i have to i...,"[thoughts, feel, believable, imagine, i’m, cer...","[thought, feel, believ, imagin, i’m, certain, ...","[thought, feel, believ, imagin, i’m, certain, ..."
4,txl82i,Im proud of myself Yeah finally ate breakfast ...,2,15,2022-04-06 08:39:10-04:00,im proud of myself yeah finally ate breakfast ...,"[im, proud, yeah, finally, ate, breakfast, mor...","[im, proud, yeah, final, ate, breakfast, morn,...","[im, proud, yeah, final, ate, breakfast, morn,..."
...,...,...,...,...,...,...,...,...,...
991,tq182f,Awful intrusive thoughts and hard to fight com...,1,7,2022-03-28 00:30:18-04:00,awful intrusive thoughts and hard to fight com...,"[awful, intrusive, thoughts, hard, fight, comp...","[aw, intrus, thought, hard, fight, compuls, gu...","[aw, intrus, thought, hard, fight, compuls, gu..."
992,tq5whw,What is happening to me ? Hello\n\nJust some r...,0,2,2022-03-28 06:03:19-04:00,what is happening to me hello just some resume...,"[happening, hello, resume, maybe, understand, ...","[happen, hello, resum, mayb, understand, situa...","[happen, hello, resum, mayb, understand, situa..."
993,tq0med,How to stop thinking about “what could have be...,1,6,2022-03-27 23:53:54-04:00,how to stop thinking about “what could have be...,"[stop, thinking, “what, could, been”, keep, ge...","[stop, think, “what, could, been”, keep, get, ...","[stop, think, “what, could, been”, keep, get, ..."
994,tq1kii,FEAR ocd Who else feels like they are fearful ...,1,4,2022-03-28 00:51:46-04:00,fear ocd who else feels like they are fearful ...,"[fear, ocd, else, feels, like, fearful, every,...","[fear, ocd, els, feel, like, fear, everi, nois...","[fear, ocd, els, feel, like, fear, everi, nois..."
995,tq2ndk,Manifesting So are we all just manifesting our...,2,5,2022-03-28 02:02:21-04:00,manifesting so are we all just manifesting our...,"[manifesting, manifesting, problems, what’s]","[manifest, manifest, problem, what’]","[manifest, manifest, problem, what’]"

In [ ]:
#combine tokenize words into sentance
ocd1["Text"] = [' '.join(t) for t in ocd1["lemmatizing"]]
ocd1

,ID,Post_Text,Total_Comments,Score,Post_Created,clean_text,tokenization,stemming,lemmatizing,Text
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00,please read this before posting about feeling ...,"[please, read, posting, feeling, suicidal, inc...","[pleas, read, post, feel, suicid, increas, num...","[pleas, read, post, feel, suicid, increas, num...",pleas read post feel suicid increas number pos...
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00,note about rules and reporting to mods modmail...,"[note, rules, reporting, mods, modmail, debate...","[note, rule, report, mod, modmail, debat, club...","[note, rule, report, mod, modmail, debat, club...",note rule report mod modmail debat club rule s...
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00,does it bother anyone else how being mentally ...,"[bother, anyone, else, mentally, ill, “normali...","[bother, anyon, els, mental, ill, “normalized”...","[bother, anyon, els, mental, ill, “normalized”...",bother anyon els mental ill “normalized” gen z...
3,txkoyq,why do thoughts feel so believable? I have to ...,14,27,2022-04-06 08:09:40-04:00,why do thoughts feel so believable i have to i...,"[thoughts, feel, believable, imagine, i’m, cer...","[thought, feel, believ, imagin, i’m, certain, ...","[thought, feel, believ, imagin, i’m, certain, ...",thought feel believ imagin i’m certain scenari...
4,txl82i,Im proud of myself Yeah finally ate breakfast ...,2,15,2022-04-06 08:39:10-04:00,im proud of myself yeah finally ate breakfast ...,"[im, proud, yeah, finally, ate, breakfast, mor...","[im, proud, yeah, final, ate, breakfast, morn,...","[im, proud, yeah, final, ate, breakfast, morn,...",im proud yeah final ate breakfast morn didn’t ...
...,...,...,...,...,...,...,...,...,...,...
991,tq182f,Awful intrusive thoughts and hard to fight com...,1,7,2022-03-28 00:30:18-04:00,awful intrusive thoughts and hard to fight com...,"[awful, intrusive, thoughts, hard, fight, comp...","[aw, intrus, thought, hard, fight, compuls, gu...","[aw, intrus, thought, hard, fight, compuls, gu...",aw intrus thought hard fight compuls gum feel ...
992,tq5whw,What is happening to me ? Hello\n\nJust some r...,0,2,2022-03-28 06:03:19-04:00,what is happening to me hello just some resume...,"[happening, hello, resume, maybe, understand, ...","[happen, hello, resum, mayb, understand, situa...","[happen, hello, resum, mayb, understand, situa...",happen hello resum mayb understand situat im g...
993,tq0med,How to stop thinking about “what could have be...,1,6,2022-03-27 23:53:54-04:00,how to stop thinking about “what could have be...,"[stop, thinking, “what, could, been”, keep, ge...","[stop, think, “what, could, been”, keep, get, ...","[stop, think, “what, could, been”, keep, get, ...",stop think “what could been” keep get rumin lo...
994,tq1kii,FEAR ocd Who else feels like they are fearful ...,1,4,2022-03-28 00:51:46-04:00,fear ocd who else feels like they are fearful ...,"[fear, ocd, else, feels, like, fearful, every,...","[fear, ocd, els, feel, like, fear, everi, nois...","[fear, ocd, els, feel, like, fear, everi, nois...",fear ocd els feel like fear everi nois chang a...
995,tq2ndk,Manifesting So are we all just manifesting our...,2,5,2022-03-28 02:02:21-04:00,manifesting so are we all just manifesting our...,"[manifesting, manifesting, problems, what’s]","[manifest, manifest, problem, what’]","[manifest, manifest, problem, what’]",manifest manifest problem what’

In [ ]:
df_ocd1 = ocd1[["ID", "Post_Text", "Total_Comments", "Score", "Post_Created", "Text"]]
df_ocd1

,ID,Post_Text,Total_Comments,Score,Post_Created,Text
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00,pleas read post feel suicid increas number pos...
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00,note rule report mod modmail debat club rule s...
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00,bother anyon els mental ill “normalized” gen z...
3,txkoyq,why do thoughts feel so believable? I have to ...,14,27,2022-04-06 08:09:40-04:00,thought feel believ imagin i’m certain scenari...
4,txl82i,Im proud of myself Yeah finally ate breakfast ...,2,15,2022-04-06 08:39:10-04:00,im proud yeah final ate breakfast morn didn’t ...
...,...,...,...,...,...,...
991,tq182f,Awful intrusive thoughts and hard to fight com...,1,7,2022-03-28 00:30:18-04:00,aw intrus thought hard fight compuls gum feel ...
992,tq5whw,What is happening to me ? Hello\n\nJust some r...,0,2,2022-03-28 06:03:19-04:00,happen hello resum mayb understand situat im g...
993,tq0med,How to stop thinking about “what could have be...,1,6,2022-03-27 23:53:54-04:00,stop think “what could been” keep get rumin lo...
994,tq1kii,FEAR ocd Who else feels like they are fearful ...,1,4,2022-03-28 00:51:46-04:00,fear ocd els feel like fear everi nois chang a...
995,tq2ndk,Manifesting So are we all just manifesting our...,2,5,2022-03-28 02:02:21-04:00,manifest manifest problem what’

In [ ]:
#Getting sentiment scores
from textblob import TextBlob

In [ ]:
## Define a function which can be applied to calculate the score for the whole dataset
 
def senti(x):
    return TextBlob(x).sentiment  
 
df_ocd1['senti_score'] = df_ocd1['Text'].apply(senti)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df_ocd1
#As it can be observed there are two scores: the first score is sentiment polarity which tells if the sentiment is positive or negative 
  #and the second score is subjectivity score to tell how subjective is the text.
#The score indicates how negative or positive the overall text analyzed is. Anything below a score of -0.05 we tag as negative 
  #and anything above 0.05 we tag as positive. Anything in between inclusively, we tag as neutral.

,ID,Post_Text,Total_Comments,Score,Post_Created,Text,senti_score
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00,pleas read post feel suicid increas number pos...,"(0.1554683742183742, 0.35688532146865476)"
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00,note rule report mod modmail debat club rule s...,"(0.0, 0.3888888888888889)"
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00,bother anyon els mental ill “normalized” gen z...,"(-0.07714285714285715, 0.5914285714285714)"
3,txkoyq,why do thoughts feel so believable? I have to ...,14,27,2022-04-06 08:09:40-04:00,thought feel believ imagin i’m certain scenari...,"(-0.27714285714285714, 0.48761904761904756)"
4,txl82i,Im proud of myself Yeah finally ate breakfast ...,2,15,2022-04-06 08:39:10-04:00,im proud yeah final ate breakfast morn didn’t ...,"(0.3333333333333333, 0.7999999999999999)"
...,...,...,...,...,...,...,...
991,tq182f,Awful intrusive thoughts and hard to fight com...,1,7,2022-03-28 00:30:18-04:00,aw intrus thought hard fight compuls gum feel ...,"(-0.12648809523809526, 0.519345238095238)"
992,tq5whw,What is happening to me ? Hello\n\nJust some r...,0,2,2022-03-28 06:03:19-04:00,happen hello resum mayb understand situat im g...,"(-0.0016886552600838118, 0.49582388510959935)"
993,tq0med,How to stop thinking about “what could have be...,1,6,2022-03-27 23:53:54-04:00,stop think “what could been” keep get rumin lo...,"(0.1, 0.4)"
994,tq1kii,FEAR ocd Who else feels like they are fearful ...,1,4,2022-03-28 00:51:46-04:00,fear ocd els feel like fear everi nois chang a...,"(0.04633838383838384, 0.510479797979798)"
995,tq2ndk,Manifesting So are we all just manifesting our...,2,5,2022-03-28 02:02:21-04:00,manifest manifest problem what’,"(0.0, 0.0)"

In [ ]:
df_ocd1["senti_score"][1]

Sentiment(polarity=0.0, subjectivity=0.3888888888888889)

In [ ]:
df_ocd1["polarity"] = [t[0] for t in df_ocd1["senti_score"]]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_ocd1["polarity"][1]

0.0

In [ ]:
df_ocd1["type"] = ["negative" if t <= -0.05 else "positive" if t >= 0.05 else "nuetral" for t in df_ocd1["polarity"]]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_ocd1

,ID,Post_Text,Total_Comments,Score,Post_Created,Text,senti_score,polarity,type
0,q4zeo1,Please read this before posting about feeling ...,67,1009,2021-10-09 22:33:00-04:00,pleas read post feel suicid increas number pos...,"(0.1554683742183742, 0.35688532146865476)",0.155468,positive
1,qhd762,Note about rules and reporting to mods Mod-mai...,17,82,2021-10-27 22:49:36-04:00,note rule report mod modmail debat club rule s...,"(0.0, 0.3888888888888889)",0.000000,nuetral
2,txflc2,Does it bother anyone else how being mentally ...,49,129,2022-04-06 02:17:04-04:00,bother anyon els mental ill “normalized” gen z...,"(-0.07714285714285715, 0.5914285714285714)",-0.077143,negative
3,txkoyq,why do thoughts feel so believable? I have to ...,14,27,2022-04-06 08:09:40-04:00,thought feel believ imagin i’m certain scenari...,"(-0.27714285714285714, 0.48761904761904756)",-0.277143,negative
4,txl82i,Im proud of myself Yeah finally ate breakfast ...,2,15,2022-04-06 08:39:10-04:00,im proud yeah final ate breakfast morn didn’t ...,"(0.3333333333333333, 0.7999999999999999)",0.333333,positive
...,...,...,...,...,...,...,...,...,...
991,tq182f,Awful intrusive thoughts and hard to fight com...,1,7,2022-03-28 00:30:18-04:00,aw intrus thought hard fight compuls gum feel ...,"(-0.12648809523809526, 0.519345238095238)",-0.126488,negative
992,tq5whw,What is happening to me ? Hello\n\nJust some r...,0,2,2022-03-28 06:03:19-04:00,happen hello resum mayb understand situat im g...,"(-0.0016886552600838118, 0.49582388510959935)",-0.001689,nuetral
993,tq0med,How to stop thinking about “what could have be...,1,6,2022-03-27 23:53:54-04:00,stop think “what could been” keep get rumin lo...,"(0.1, 0.4)",0.100000,positive
994,tq1kii,FEAR ocd Who else feels like they are fearful ...,1,4,2022-03-28 00:51:46-04:00,fear ocd els feel like fear everi nois chang a...,"(0.04633838383838384, 0.510479797979798)",0.046338,nuetral
995,tq2ndk,Manifesting So are we all just manifesting our...,2,5,2022-03-28 02:02:21-04:00,manifest manifest problem what’,"(0.0, 0.0)",0.000000,nuetral

In [ ]:
df_ocd1.to_csv('HIV_POST.csv',index=False)

#Code for Comment_Text

In [ ]:
hiv2 = pd.read_csv("https://raw.githubusercontent.com/SrushtiChauhan/Test-2022/main/HIV_comments_individual.csv", 
                             on_bad_lines='skip');

In [ ]:
print('HIV Comments data:', hiv2.shape)

HIV Comments data: (3861, 4)

In [ ]:
hiv2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3861 entries, 0 to 3860
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               3861 non-null   object
 1   Comment          3861 non-null   object
 2   Comment_Created  3861 non-null   object
 3   Score            3861 non-null   int64
dtypes: int64(1), object(3)
memory usage: 120.8+ KB

In [ ]:
hiv2.describe()

             Score
count  3861.000000
mean      1.164724
std       0.686893
min     -10.000000
25%       1.000000
50%       1.000000
75%       1.000000
max       8.000000

In [ ]:
hiv2.isnull().sum()

ID                 0
Comment            0
Comment_Created    0
Score              0
dtype: int64

In [ ]:
hiv2["Comment"] = hiv2["Comment"].str.replace("[deleted]","");
hiv2["Comment"] = hiv2["Comment"].str.replace("[removed]","");

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

In [ ]:
hiv2.isnull().sum()

ID                 0
Comment            0
Comment_Created    0
Score              0
dtype: int64

In [ ]:
# Selecting duplicate rows except first
# occurrence based on all columns
duplicate = hiv2[hiv2.duplicated()]
 
print("Duplicate Rows :")
 
# Print the resultant Dataframe
duplicate

Duplicate Rows :

Empty DataFrame
Columns: [ID, Comment, Comment_Created, Score]
Index: []

In [ ]:
#Data Pre-Processing
hiv2.columns

Index(['ID', 'Comment', 'Comment_Created', 'Score'], dtype='object')

In [ ]:
hiv2.head(3)

       ID                            Comment      Comment_Created  Score
0  twwkp4  H a s a 3 nhs. O a ia a a his pin  2022-04-05 15:33:54      2
1  twwkp4  H a s a 3 nhs. O a ia a a his pin  2022-04-05 15:34:11      1
2  twvhhs                            Ys i is  2022-04-05 14:06:11      1

In [ ]:
#Convert comments data into lower case
hiv2['clean_text'] = hiv2["Comment"].str.lower()
hiv2

,ID,Comment,Comment_Created,Score,clean_text
0,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:33:54,2,h a s a 3 nhs. o a ia a a his pin
1,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:34:11,1,h a s a 3 nhs. o a ia a a his pin
2,twvhhs,Ys i is,2022-04-05 14:06:11,1,ys i is
3,twvhhs,Af hw any ays,2022-04-05 15:26:43,1,af hw any ays
4,twvhhs,Aun 67 ays,2022-04-05 15:31:13,1,aun 67 ays
...,...,...,...,...,...
3856,1m4eey,yah :D,2013-09-11 18:11:55,1,yah :d
3857,1n8vrn,"G a c, n i.",2013-09-27 14:31:51,1,"g a c, n i."
3858,1n8vrn,"Ww, is kawb jus ik, MIA a his pin? This pac n...",2013-09-28 22:02:32,2,"ww, is kawb jus ik, mia a his pin? this pac n..."
3859,1n8vrn,[],2013-09-27 14:34:53,-2,[]
3860,1n8vrn,A as I n' ha hps...,2013-09-27 15:49:20,2,a as i n' ha hps...

In [ ]:
#Autocorrect and spelling mistake correction
#spell = Speller(lang='en')

#hiv2["clean_text"] = [spell(t) for t in hiv2["clean_text"]]
#hiv2

In [ ]:
#Remove punctuation and special characters from text data
hiv2["clean_text"] = [clean_text(t) for t in hiv2['clean_text']]
hiv2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ID,Comment,Comment_Created,Score,clean_text
0,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:33:54,2,h a s a nhs o a ia a a his pin
1,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:34:11,1,h a s a nhs o a ia a a his pin
2,twvhhs,Ys i is,2022-04-05 14:06:11,1,ys i is
3,twvhhs,Af hw any ays,2022-04-05 15:26:43,1,af hw any ays
4,twvhhs,Aun 67 ays,2022-04-05 15:31:13,1,aun ays
...,...,...,...,...,...
3855,1m4eey,W wu b in uch cs agn hn!,2013-09-11 18:06:28,1,w wu b in uch cs agn hn
3856,1m4eey,yah :D,2013-09-11 18:11:55,1,yah d
3857,1n8vrn,"G a c, n i.",2013-09-27 14:31:51,1,g a c n i
3858,1n8vrn,"Ww, is kawb jus ik, MIA a his pin? This pac n...",2013-09-28 22:02:32,2,ww is kawb jus ik mia a his pin this pac ns s ...
3860,1n8vrn,A as I n' ha hps...,2013-09-27 15:49:20,2,a as i n ha hps

In [ ]:
hiv2 = hiv2[hiv2["clean_text"].str.len() != 0]

In [ ]:
#Tokenization
# Create a reference variable for Class WhitespaceTokenizer
tk = WhitespaceTokenizer()

hiv2["tokenization"] = [tk.tokenize(t) for t in hiv2["clean_text"]]
hiv2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,ID,Comment,Comment_Created,Score,clean_text,tokenization
0,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:33:54,2,h a s a nhs o a ia a a his pin,"[h, a, s, a, nhs, o, a, ia, a, a, his, pin]"
1,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:34:11,1,h a s a nhs o a ia a a his pin,"[h, a, s, a, nhs, o, a, ia, a, a, his, pin]"
2,twvhhs,Ys i is,2022-04-05 14:06:11,1,ys i is,"[ys, i, is]"
3,twvhhs,Af hw any ays,2022-04-05 15:26:43,1,af hw any ays,"[af, hw, any, ays]"
4,twvhhs,Aun 67 ays,2022-04-05 15:31:13,1,aun ays,"[aun, ays]"
...,...,...,...,...,...,...
3855,1m4eey,W wu b in uch cs agn hn!,2013-09-11 18:06:28,1,w wu b in uch cs agn hn,"[w, wu, b, in, uch, cs, agn, hn]"
3856,1m4eey,yah :D,2013-09-11 18:11:55,1,yah d,"[yah, d]"
3857,1n8vrn,"G a c, n i.",2013-09-27 14:31:51,1,g a c n i,"[g, a, c, n, i]"
3858,1n8vrn,"Ww, is kawb jus ik, MIA a his pin? This pac n...",2013-09-28 22:02:32,2,ww is kawb jus ik mia a his pin this pac ns s ...,"[ww, is, kawb, jus, ik, mia, a, his, pin, this..."
3860,1n8vrn,A as I n' ha hps...,2013-09-27 15:49:20,2,a as i n ha hps,"[a, as, i, n, ha, hps]"

In [ ]:
hiv2['tokenization'] = hiv2['tokenization'].apply(lambda x: [w for w in x if not w in 
                              stopwords.words('english')]) # Stem every word.
hiv2 # Print dataframe.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,ID,Comment,Comment_Created,Score,clean_text,tokenization
0,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:33:54,2,h a s a nhs o a ia a a his pin,"[h, nhs, ia, pin]"
1,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:34:11,1,h a s a nhs o a ia a a his pin,"[h, nhs, ia, pin]"
2,twvhhs,Ys i is,2022-04-05 14:06:11,1,ys i is,[ys]
3,twvhhs,Af hw any ays,2022-04-05 15:26:43,1,af hw any ays,"[af, hw, ays]"
4,twvhhs,Aun 67 ays,2022-04-05 15:31:13,1,aun ays,"[aun, ays]"
...,...,...,...,...,...,...
3855,1m4eey,W wu b in uch cs agn hn!,2013-09-11 18:06:28,1,w wu b in uch cs agn hn,"[w, wu, b, uch, cs, agn, hn]"
3856,1m4eey,yah :D,2013-09-11 18:11:55,1,yah d,[yah]
3857,1n8vrn,"G a c, n i.",2013-09-27 14:31:51,1,g a c n i,"[g, c, n]"
3858,1n8vrn,"Ww, is kawb jus ik, MIA a his pin? This pac n...",2013-09-28 22:02:32,2,ww is kawb jus ik mia a his pin this pac ns s ...,"[ww, kawb, jus, ik, mia, pin, pac, ns]"
3860,1n8vrn,A as I n' ha hps...,2013-09-27 15:49:20,2,a as i n ha hps,"[n, ha, hps]"

In [ ]:
ps = PorterStemmer()

In [ ]:
#Stemming
hiv2['stemming'] = hiv2['tokenization'].apply(lambda x: [ps.stem(y) for y in x]) # Stem every word.
hiv2 # Print dataframe.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ID,Comment,Comment_Created,Score,clean_text,tokenization,stemming
0,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:33:54,2,h a s a nhs o a ia a a his pin,"[h, nhs, ia, pin]","[h, nh, ia, pin]"
1,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:34:11,1,h a s a nhs o a ia a a his pin,"[h, nhs, ia, pin]","[h, nh, ia, pin]"
2,twvhhs,Ys i is,2022-04-05 14:06:11,1,ys i is,[ys],[ys]
3,twvhhs,Af hw any ays,2022-04-05 15:26:43,1,af hw any ays,"[af, hw, ays]","[af, hw, ay]"
4,twvhhs,Aun 67 ays,2022-04-05 15:31:13,1,aun ays,"[aun, ays]","[aun, ay]"
...,...,...,...,...,...,...,...
3855,1m4eey,W wu b in uch cs agn hn!,2013-09-11 18:06:28,1,w wu b in uch cs agn hn,"[w, wu, b, uch, cs, agn, hn]","[w, wu, b, uch, cs, agn, hn]"
3856,1m4eey,yah :D,2013-09-11 18:11:55,1,yah d,[yah],[yah]
3857,1n8vrn,"G a c, n i.",2013-09-27 14:31:51,1,g a c n i,"[g, c, n]","[g, c, n]"
3858,1n8vrn,"Ww, is kawb jus ik, MIA a his pin? This pac n...",2013-09-28 22:02:32,2,ww is kawb jus ik mia a his pin this pac ns s ...,"[ww, kawb, jus, ik, mia, pin, pac, ns]","[ww, kawb, ju, ik, mia, pin, pac, ns]"
3860,1n8vrn,A as I n' ha hps...,2013-09-27 15:49:20,2,a as i n ha hps,"[n, ha, hps]","[n, ha, hp]"

In [ ]:
lemmatizer = WordNetLemmatizer()

In [ ]:
#Lemmatization
# a denotes adjective in "pos"
hiv2['lemmatizing'] = hiv2['stemming'].apply(lambda x: [lemmatizer.lemmatize(y, pos ="a") for y in x]) # Stem every word.
hiv2 # Print dataframe.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,ID,Comment,Comment_Created,Score,clean_text,tokenization,stemming,lemmatizing
0,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:33:54,2,h a s a nhs o a ia a a his pin,"[h, nhs, ia, pin]","[h, nh, ia, pin]","[h, nh, ia, pin]"
1,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:34:11,1,h a s a nhs o a ia a a his pin,"[h, nhs, ia, pin]","[h, nh, ia, pin]","[h, nh, ia, pin]"
2,twvhhs,Ys i is,2022-04-05 14:06:11,1,ys i is,[ys],[ys],[ys]
3,twvhhs,Af hw any ays,2022-04-05 15:26:43,1,af hw any ays,"[af, hw, ays]","[af, hw, ay]","[af, hw, ay]"
4,twvhhs,Aun 67 ays,2022-04-05 15:31:13,1,aun ays,"[aun, ays]","[aun, ay]","[aun, ay]"
...,...,...,...,...,...,...,...,...
3855,1m4eey,W wu b in uch cs agn hn!,2013-09-11 18:06:28,1,w wu b in uch cs agn hn,"[w, wu, b, uch, cs, agn, hn]","[w, wu, b, uch, cs, agn, hn]","[w, wu, b, uch, cs, agn, hn]"
3856,1m4eey,yah :D,2013-09-11 18:11:55,1,yah d,[yah],[yah],[yah]
3857,1n8vrn,"G a c, n i.",2013-09-27 14:31:51,1,g a c n i,"[g, c, n]","[g, c, n]","[g, c, n]"
3858,1n8vrn,"Ww, is kawb jus ik, MIA a his pin? This pac n...",2013-09-28 22:02:32,2,ww is kawb jus ik mia a his pin this pac ns s ...,"[ww, kawb, jus, ik, mia, pin, pac, ns]","[ww, kawb, ju, ik, mia, pin, pac, ns]","[ww, kawb, ju, ik, mia, pin, pac, ns]"
3860,1n8vrn,A as I n' ha hps...,2013-09-27 15:49:20,2,a as i n ha hps,"[n, ha, hps]","[n, ha, hp]","[n, ha, hp]"

In [ ]:
#combine tokenize words into sentance
hiv2["Text"] = [' '.join(t) for t in hiv2["lemmatizing"]]
hiv2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ID,Comment,Comment_Created,Score,clean_text,tokenization,stemming,lemmatizing,Text
0,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:33:54,2,h a s a nhs o a ia a a his pin,"[h, nhs, ia, pin]","[h, nh, ia, pin]","[h, nh, ia, pin]",h nh ia pin
1,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:34:11,1,h a s a nhs o a ia a a his pin,"[h, nhs, ia, pin]","[h, nh, ia, pin]","[h, nh, ia, pin]",h nh ia pin
2,twvhhs,Ys i is,2022-04-05 14:06:11,1,ys i is,[ys],[ys],[ys],ys
3,twvhhs,Af hw any ays,2022-04-05 15:26:43,1,af hw any ays,"[af, hw, ays]","[af, hw, ay]","[af, hw, ay]",af hw ay
4,twvhhs,Aun 67 ays,2022-04-05 15:31:13,1,aun ays,"[aun, ays]","[aun, ay]","[aun, ay]",aun ay
...,...,...,...,...,...,...,...,...,...
3855,1m4eey,W wu b in uch cs agn hn!,2013-09-11 18:06:28,1,w wu b in uch cs agn hn,"[w, wu, b, uch, cs, agn, hn]","[w, wu, b, uch, cs, agn, hn]","[w, wu, b, uch, cs, agn, hn]",w wu b uch cs agn hn
3856,1m4eey,yah :D,2013-09-11 18:11:55,1,yah d,[yah],[yah],[yah],yah
3857,1n8vrn,"G a c, n i.",2013-09-27 14:31:51,1,g a c n i,"[g, c, n]","[g, c, n]","[g, c, n]",g c n
3858,1n8vrn,"Ww, is kawb jus ik, MIA a his pin? This pac n...",2013-09-28 22:02:32,2,ww is kawb jus ik mia a his pin this pac ns s ...,"[ww, kawb, jus, ik, mia, pin, pac, ns]","[ww, kawb, ju, ik, mia, pin, pac, ns]","[ww, kawb, ju, ik, mia, pin, pac, ns]",ww kawb ju ik mia pin pac ns
3860,1n8vrn,A as I n' ha hps...,2013-09-27 15:49:20,2,a as i n ha hps,"[n, ha, hps]","[n, ha, hp]","[n, ha, hp]",n ha hp

In [ ]:
hiv2.isnull().sum()

ID                 0
Comment            0
Comment_Created    0
Score              0
clean_text         0
tokenization       0
stemming           0
lemmatizing        0
Text               0
dtype: int64

In [ ]:
hiv2.columns

Index(['ID', 'Comment', 'Comment_Created', 'Score', 'clean_text',
       'tokenization', 'stemming', 'lemmatizing', 'Text'],
      dtype='object')

In [ ]:
df_hiv2 = hiv2[["ID", "Comment", "Comment_Created", "Score", "Text"]]
df_hiv2

,ID,Comment,Comment_Created,Score,Text
0,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:33:54,2,h nh ia pin
1,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:34:11,1,h nh ia pin
2,twvhhs,Ys i is,2022-04-05 14:06:11,1,ys
3,twvhhs,Af hw any ays,2022-04-05 15:26:43,1,af hw ay
4,twvhhs,Aun 67 ays,2022-04-05 15:31:13,1,aun ay
...,...,...,...,...,...
3855,1m4eey,W wu b in uch cs agn hn!,2013-09-11 18:06:28,1,w wu b uch cs agn hn
3856,1m4eey,yah :D,2013-09-11 18:11:55,1,yah
3857,1n8vrn,"G a c, n i.",2013-09-27 14:31:51,1,g c n
3858,1n8vrn,"Ww, is kawb jus ik, MIA a his pin? This pac n...",2013-09-28 22:02:32,2,ww kawb ju ik mia pin pac ns
3860,1n8vrn,A as I n' ha hps...,2013-09-27 15:49:20,2,n ha hp

In [ ]:
#Getting sentiment scores
from textblob import TextBlob

In [ ]:
## Define a function which can be applied to calculate the score for the whole dataset
 
def senti(x):
    return TextBlob(x).sentiment  
 
df_hiv2['senti_score'] = df_hiv2['Text'].apply(senti)
df_hiv2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ID,Comment,Comment_Created,Score,Text,senti_score
0,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:33:54,2,h nh ia pin,"(0.0, 0.0)"
1,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:34:11,1,h nh ia pin,"(0.0, 0.0)"
2,twvhhs,Ys i is,2022-04-05 14:06:11,1,ys,"(0.0, 0.0)"
3,twvhhs,Af hw any ays,2022-04-05 15:26:43,1,af hw ay,"(0.0, 0.0)"
4,twvhhs,Aun 67 ays,2022-04-05 15:31:13,1,aun ay,"(0.0, 0.0)"
...,...,...,...,...,...,...
3855,1m4eey,W wu b in uch cs agn hn!,2013-09-11 18:06:28,1,w wu b uch cs agn hn,"(0.0, 0.0)"
3856,1m4eey,yah :D,2013-09-11 18:11:55,1,yah,"(0.0, 0.0)"
3857,1n8vrn,"G a c, n i.",2013-09-27 14:31:51,1,g c n,"(0.0, 0.0)"
3858,1n8vrn,"Ww, is kawb jus ik, MIA a his pin? This pac n...",2013-09-28 22:02:32,2,ww kawb ju ik mia pin pac ns,"(0.0, 0.0)"
3860,1n8vrn,A as I n' ha hps...,2013-09-27 15:49:20,2,n ha hp,"(0.0, 0.0)"

In [ ]:
df_hiv2["polarity"] = [t[0] for t in df_hiv2["senti_score"]]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_hiv2["type"] = ["negative" if t <= -0.05 else "positive" if t >= 0.05 else "nuetral" for t in df_hiv2["polarity"]]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_hiv2

,ID,Comment,Comment_Created,Score,Text,senti_score,polarity,type
0,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:33:54,2,h nh ia pin,"(0.0, 0.0)",0.0,nuetral
1,twwkp4,H a s a 3 nhs. O a ia a a his pin,2022-04-05 15:34:11,1,h nh ia pin,"(0.0, 0.0)",0.0,nuetral
2,twvhhs,Ys i is,2022-04-05 14:06:11,1,ys,"(0.0, 0.0)",0.0,nuetral
3,twvhhs,Af hw any ays,2022-04-05 15:26:43,1,af hw ay,"(0.0, 0.0)",0.0,nuetral
4,twvhhs,Aun 67 ays,2022-04-05 15:31:13,1,aun ay,"(0.0, 0.0)",0.0,nuetral
...,...,...,...,...,...,...,...,...
3855,1m4eey,W wu b in uch cs agn hn!,2013-09-11 18:06:28,1,w wu b uch cs agn hn,"(0.0, 0.0)",0.0,nuetral
3856,1m4eey,yah :D,2013-09-11 18:11:55,1,yah,"(0.0, 0.0)",0.0,nuetral
3857,1n8vrn,"G a c, n i.",2013-09-27 14:31:51,1,g c n,"(0.0, 0.0)",0.0,nuetral
3858,1n8vrn,"Ww, is kawb jus ik, MIA a his pin? This pac n...",2013-09-28 22:02:32,2,ww kawb ju ik mia pin pac ns,"(0.0, 0.0)",0.0,nuetral
3860,1n8vrn,A as I n' ha hps...,2013-09-27 15:49:20,2,n ha hp,"(0.0, 0.0)",0.0,nuetral

In [ ]:
df_hiv2['type'].value_counts()

nuetral     3177
negative     324
positive     228
Name: type, dtype: int64

In [ ]:
df_hiv2.to_csv('HIV_COMMENT.csv',index=False)